meta_product_name: "CityDog"
meta_title: "CityDog - Friendly Venues for Furry Friends"
meta_description: "Find dog friendly bars, restaurants or cafés in your neighbourhood"
meta_image: "og_image.jpg"
